# Generated by Django 5.0.3 on 2024-03-07 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basededatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id_usuario',
            new_name='dni',
        ),
    ]
